<?php
/**
 * TrackTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OneMusicAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OneMusicAPI
 *
 * OneMusicAPI is a low cost music metadata API
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: dan@elstensoftware.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OneMusicAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * TrackTest Class Doc Comment
 *
 * @category    Class
 * @description Track
 * @package     OneMusicAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class TrackTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Track"
     */
    public function testTrack()
    {
    }

    /**
     * Test attribute "source_uri"
     */
    public function testPropertySourceUri()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "number"
     */
    public function testPropertyNumber()
    {
    }

    /**
     * Test attribute "artists"
     */
    public function testPropertyArtists()
    {
    }

    /**
     * Test attribute "match"
     */
    public function testPropertyMatch()
    {
    }

    /**
     * Test attribute "releases"
     */
    public function testPropertyReleases()
    {
    }

    /**
     * Test attribute "uris"
     */
    public function testPropertyUris()
    {
    }

    /**
     * Test attribute "composers"
     */
    public function testPropertyComposers()
    {
    }

    /**
     * Test attribute "isrc"
     */
    public function testPropertyIsrc()
    {
    }

    /**
     * Test attribute "score"
     */
    public function testPropertyScore()
    {
    }
}
